services:
  shoroksheba_database:
    image: mysql:8.0
    container_name: shoroksheba_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shoroksheba
      MYSQL_DATABASE: shoroksheba
      MYSQL_USER: shoroksheba
      MYSQL_PASSWORD: shoroksheba
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
